include: package:flutter_lints/flutter.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
#linter:
#  rules:
#    prefer_single_quotes: true
#    deprecated_member_use_from_same_package: false
#    missing_required_param: false

analyzer:
#  errors:
#    omit_local_variable_types: ignore
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true
